name: CI Runner

on:
  workflow_call:
    inputs:
      distro:     {type: string, default: 'alpine'}
      vendor:     {type: string, default: 'linux'}
      arch:       {type: string, default: 'x86_64'}
      image:      {type: string, default: 'alpine:latest'}
      features:   {type: string, default: 'base gnu py3pe gnuefi'}
      toolchain:  {type: string, default: ''}
      build_dir:  {type: string, default: 'build'}

permissions:
  packages: write
  contents: read

jobs:
  job_id:
    # Wait for https://github.com/orgs/community/discussions/8945
    name: Get Job ID
    runs-on: ubuntu-latest
    outputs:
      job_id: ${{ steps.job_id.outputs.job_id }}
    steps:
      - id: job_id
        uses: qoomon/actions--context@v4

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: job_id

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build on Platform
      uses: ./.github/actions/run-on-platform
      with: 
        distro:    ${{ inputs.distro }}
        vendor:    ${{ inputs.vendor }}
        arch:      ${{ inputs.arch }}
        image:     ${{ inputs.image }}
        features:  ${{ inputs.features }}
        toolchain: ${{ inputs.toolchain }}
        build_dir: ${{ inputs.build_dir }}
        run:        build
    
    - uses: actions/upload-artifact@v4
      with:
        name: fwupd-efi-${{ inputs.arch }}-${{ github.run_id }}-${{ needs.job_id.outputs.job_id }}
        path: build/efi/*.efi
 
  run:
    name: Execute 
    runs-on: ubuntu-latest
    needs: [job_id, build]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: fwupd-efi-${{ inputs.arch }}-${{ github.run_id }}-${{ needs.job_id.outputs.job_id }}
        path: build/efi/

    - name: Test on Platform
      uses: ./.github/actions/run-on-platform
      with: 
        distro:     ${{ inputs.distro }}
        vendor:     ${{ inputs.vendor }}
        arch:       ${{ inputs.arch }}
        image:      ${{ inputs.image }}
        features:   'qemu edk2'
        build_dir:  ${{ inputs.build_dir }}
        run:        run

    - uses: actions/upload-artifact@v4
      with:
        name: fwupd-log-${{ inputs.arch }}-${{ github.run_id }}-${{ needs.job_id.outputs.job_id }}
        path: build/*.efi.log

  test:
    name: Validate 
    runs-on: ubuntu-latest
    needs: [job_id, build, run]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: fwupd-log-${{ inputs.arch }}-${{ github.run_id }}-${{ needs.job_id.outputs.job_id }}

    - name: Validate Log
      run: |
        set -x
        ./contrib/ci_validate.sh fwupd*.log