name: CI run on latest
on:
  push:
    branches: [ ci_v2 ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image: [ alpine:latest ]
        arch: [ x86_64, i386, arm, aarch64, riscv64, loongarch64 ]
        features: [ 
          "base gnu py3pe gnuefi"
        ]

    uses: ./.github/workflows/ci_runner.yaml
    with:
      arch: ${{ matrix.arch }}
      features: ${{ matrix.features }}
      image: ${{ matrix.arch == 'loongarch64' && 'loongarch64/alpine:3.21' || 'alpine:latest' }}
