name: Continuous Integration
on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

permissions:
  contents: read

jobs:
  #pre-commit:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Refresh dependencies
  #      run: sudo apt update
  #    - name: Install dependencies
  #      run: sudo apt install shellcheck -y
  #    - name: Run pre-commit hooks
  #      run: |
  #        ./contrib/setup
  #        source venv/bin/activate
  #        sed -i "/no-commit-to-branch/,+1d" .pre-commit-config.yaml
  #        pre-commit run --all-files

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: fedora
            platform: linux/amd64
            image: fedora:latest
            buildpkg: 1
          - distro: debian
            platform: linux/amd64
            image: debian:testing
            buildpkg: 1
          - distro: debian
            platform: linux/386
            image: i386/debian:testing
            buildpkg: 1
          - distro: arch
            platform: linux/amd64
            image: archlinux/archlinux:latest
            buildpkg: 1

          - distro: ubuntu
            platform: linux/arm/v7
            image: ubuntu:rolling
          - distro: ubuntu
            platform: linux/arm64/v8
            image: ubuntu:rolling
          - distro: ubuntu
            platform: linux/riscv64
            image: ubuntu:rolling

          - distro: alpine
            platform: linux/amd64
            image: alpine:latest
          - distro: alpine
            platform: linux/386
            image: alpine:latest
          - distro: alpine
            platform: linux/arm/v7
            image: alpine:latest
          - distro: alpine
            platform: linux/arm64/v8
            image: alpine:latest
          - distro: alpine
            platform: linux/riscv64
            image: alpine:latest
            
          - distro: alpine-llvm
            platform: linux/amd64
            image: alpine:latest
          - distro: alpine-llvm
            platform: linux/386
            image: alpine:latest
          - distro: alpine-llvm
            platform: linux/arm/v7
            image: alpine:latest
          - distro: alpine-llvm
            platform: linux/arm64/v8
            image: alpine:latest
          - distro: alpine-llvm
            platform: linux/riscv64
            image: alpine:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Enable QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Load setup script
        id: ci_install
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: contrib/ci_install.sh

      - name: Run CI inside ${{ matrix.image }}
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: none
          distro: none
          shell: /bin/sh
          base_image: |
            --platform=${{ matrix.platform }} ${{ matrix.image }}
          dockerRunArgs: |
            --volume "${{ github.workspace }}:/work"
            --workdir /work
          # githubToken: ${{ github.token }}
          install: |
            CI_DISTRO="${{ matrix.distro }}"
            CI_BUILDPKG="${{ matrix.buildpkg }}"
            ${{ steps.ci_install.outputs.content }}
          env: |
            CI_DISTRO: ${{ matrix.distro }}
            CI_BUILDPKG: ${{ matrix.buildpkg }}
          run: |
            set -e
            ./contrib/ci.sh
