name: Continuous Integration
on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

permissions:
  contents: read

jobs:
  #pre-commit:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Refresh dependencies
  #      run: sudo apt update
  #    - name: Install dependencies
  #      run: sudo apt install shellcheck -y
  #    - name: Run pre-commit hooks
  #      run: |
  #        ./contrib/setup
  #        source venv/bin/activate
  #        sed -i "/no-commit-to-branch/,+1d" .pre-commit-config.yaml
  #        pre-commit run --all-files

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: fedora
            platform: linux/amd64
            image: fedora:latest
            buildpkg: true
          - distro: debian
            platform: linux/amd64
            image: debian:testing
            buildpkg: true
          - distro: debian
            platform: linux/386
            image: i386/debian:testing
            buildpkg: true
          - distro: arch
            platform: linux/amd64
            image: archlinux/archlinux:latest

          - distro: ubuntu
            platform: linux/amd64
            image: ubuntu:rolling
          - distro: ubuntu
            platform: linux/arm64
            image: ubuntu:rolling
          - distro: ubuntu
            platform: linux/riscv64
            image: ubuntu:rolling
          - distro: ubuntu-llvm
            platform: linux/amd64
            image: ubuntu:rolling
            llvm: true
          - distro: ubuntu-llvm
            platform: linux/arm64
            image: ubuntu:rolling
            llvm: true
          - distro: ubuntu-llvm
            platform: linux/riscv64
            image: ubuntu:rolling
            llvm: true

          - distro: alpine
            platform: linux/amd64
            image: alpine:latest
          - distro: alpine
            platform: linux/386
            image: alpine:latest
          - distro: alpine
            platform: linux/arm/v7
            image: alpine:latest
          - distro: alpine
            platform: linux/arm64/v8
            image: alpine:latest
          - distro: alpine
            platform: linux/riscv64
            image: alpine:latest
          - distro: alpine
            platform: linux/loong64
            image: ghcr.io/loong64/alpine
            continue-on-error: true # broken in binutils 2.44 https://sourceware.org/pipermail/binutils-cvs/2024-August/065576.html
            
          - distro: alpine-llvm
            platform: linux/amd64
            image: alpine:latest
            llvm: true
          - distro: alpine-llvm
            platform: linux/386
            image: alpine:latest
            llvm: true
          - distro: alpine-llvm
            platform: linux/arm/v7
            image: alpine:latest
            llvm: true
          - distro: alpine-llvm
            platform: linux/arm64/v8
            image: alpine:latest
            llvm: true
          - distro: alpine-llvm
            platform: linux/riscv64
            image: alpine:latest
            llvm: true
          - distro: alpine-llvm
            platform: linux/loong64
            image: ghcr.io/loong64/alpine
            llvm: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Enable QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Export evn vars
        run: |
          echo "CI_DISTRO=${{ matrix.distro }}" >> "$GITHUB_ENV"
          echo "CI_BUILDPKG=${{ matrix.buildpkg && '1' || '' }}" >> "$GITHUB_ENV"
          echo "LLVM=${{ matrix.llvm && '1' || '' }}" >> "$GITHUB_ENV"

      - name: Load setup script
        id: ci_install
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: contrib/ci_install.sh

      - name: Run CI inside ${{ matrix.image }}
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: none
          distro: none
          shell: /bin/sh
          base_image: |
            --platform=${{ matrix.platform }} ${{ matrix.image }}
          dockerRunArgs: |
            --volume "${{ github.workspace }}:/work"
            --workdir /work
          # githubToken: ${{ github.token }}
          install: |
            CI_DISTRO="${{ env.CI_DISTRO }}"
            CI_BUILDPKG="${{ env.CI_BUILDPKG }}"
            LLVM="${{ env.LLVM }}"
            ${{ steps.ci_install.outputs.content }}
          run: |
            set -ex
            export CI_DISTRO="${{ env.CI_DISTRO }}"
            export CI_BUILDPKG="${{ env.CI_BUILDPKG }}"
            export LLVM="${{ env.LLVM }}"
            ./contrib/ci.sh
